import { priceRarity } from './case-mechanics';
export type Food={name:string;sub:string;price:number;rarity:number;image:number;veg?:boolean;quip:string};
// Approximate milk-tea prices in thousands of VND for brands with Hanoi stores.
export const foods:Food[]=[
  {name:"Tocotoco",sub:"Trà sữa • Hà Nội",price:45,image:0,quip:""},
  {name:"Gong Cha",sub:"Trà sữa • Hà Nội",price:55,image:1,quip:""},
  {name:"Phúc Long",sub:"Trà sữa • Hà Nội",price:25,image:2,quip:""},
  {name:"The Alley",sub:"Trà sữa • Hà Nội",price:50,image:3,quip:""},
  {name:"KOI Thé",sub:"Trà sữa • Hà Nội",price:150,image:4,quip:""},
  {name:"Ding Tea",sub:"Trà sữa • Hà Nội",price:100,image:5,quip:""},
  {name:"Mixue",sub:"Trà sữa • Hà Nội",price:65,image:6,quip:""},
  {name:"Bingxue",sub:"Trà sữa • Hà Nội",price:35,image:7,veg:true,quip:""},
  {name:"Sharetea",sub:"Trà sữa • Hà Nội",price:85,image:8,quip:""},
  {name:"Chatime",sub:"Trà sữa • Hà Nội",price:45,image:9,quip:""},
  {name:"Tiger Sugar",sub:"Trà sữa • Hà Nội",price:50,image:10,quip:""},
  {name:"Xing Fu Tang",sub:"Trà sữa • Hà Nội",price:40,image:11,quip:""},
  {name:"Bobapop",sub:"Trà sữa • Hà Nội",price:45,image:12,quip:""},
  {name:"Royaltea",sub:"Trà sữa • Hà Nội",price:40,image:13,quip:""},
  {name:"Heekcaa",sub:"Trà sữa • Hà Nội",price:35,image:14,quip:""},
  {name:"Hồng Trà Ngô Gia",sub:"Trà sữa • Hà Nội",price:55,image:15,quip:""},
  {name:"Viên Viên",sub:"Trà sữa • Hà Nội",price:50,image:16,quip:""},
  {name:"Mãn Mãn",sub:"Trà sữa • Hà Nội",price:85,image:17,quip:""},
  {name:"Tam Hảo",sub:"Trà sữa • Hà Nội",price:50,image:18,quip:""},
  {name:"Phê La",sub:"Trà sữa • Hà Nội",price:45,image:19,quip:""},
  {name:"Chagee",sub:"Trà sữa • Hà Nội",price:120,image:20,veg:true,quip:""},
  {name:"Katinat",sub:"Trà sữa • Hà Nội",price:40,image:21,veg:true,quip:""},
  {name:"Pozaa Tea",sub:"Trà sữa • Hà Nội",price:25,image:22,veg:true,quip:""},
  {name:"Lucky Tea",sub:"Trà sữa • Hà Nội",price:35,image:23,veg:true,quip:""},
  {name:"Ông Bầu",sub:"Trà sữa • Hà Nội",price:100,image:24,quip:""},
  {name:"Coco",sub:"Trà sữa • Hà Nội",price:85,image:25,quip:""},
  {name:"Ten Ren",sub:"Trà sữa • Hà Nội",price:90,image:26,quip:""},
  {name:"Quickly",sub:"Trà sữa • Hà Nội",price:65,image:27,quip:""},
  {name:"LeeTee",sub:"Trà sữa • Hà Nội",price:65,image:28,quip:""},
  {name:"Milksha",sub:"Trà sữa • Hà Nội",price:80,image:29,quip:""},
  {name:"Formosa Chang",sub:"Trà sữa • Hà Nội",price:75,image:30,quip:""},
  {name:"Owl Cha",sub:"Trà sữa • Hà Nội",price:80,image:31,quip:""},
  {name:"Bamboo Cha",sub:"Trà sữa • Hà Nội",price:115,image:32,veg:true,quip:""},
  {name:"All Day Tea",sub:"Trà sữa • Hà Nội",price:55,image:33,quip:""},
  {name:"OneTwo Tea",sub:"Trà sữa • Hà Nội",price:45,image:34,quip:""},
  {name:"Tealive",sub:"Trà sữa • Hà Nội",price:35,image:35,veg:true,quip:""},
  {name:"TP Tea",sub:"Trà sữa • Hà Nội",price:75,image:36,quip:""},
  {name:"Chago",sub:"Trà sữa • Hà Nội",price:85,image:39,quip:""},
  {name:"Heytea",sub:"Trà sữa • Hà Nội",price:150,image:42,veg:true,quip:""},
].map(food=>({...food,rarity:priceRarity(food.price)}));
